spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3310/library
    driver-class-name: com.mysql.cj.jdbc.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true